global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flask-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.49.2:30036']
